version: '3.4'

services:

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: ./Store/Dockerfile
    environment:
      - ProducEndpoint=http://backend:8080
    ports:
      - "32000:8080"
    depends_on:
      - backend
  
  backend:
    image: productservice
    build:
      context: .
      dockerfile: ./Products/Dockerfile
    ports:
      - "32001:8080"
